[tools]
rust = "nightly"


[tasks]
demo = "cargo run --bin demo"
dev = "cargo run --bin dev"
watch = "mise watch dev --shell=\"fish --no-config\" --quiet --silent --wrap-process none --raw"
[tasks.fix]
run = "cargo clippy --all --all-targets -- -D warnings && cargo fmt --all"
