use std::num::ParseIntError;
use thiserror::Error;

/// Error returned when parsing a flags type generated by [`const_bitflags!`].
#[derive(Clone, Debug, Error)]
pub enum ParseFlagsError {
    #[error("empty bits")]
    Empty,
    #[error("invalid bits: {0:#x}")]
    Invalid(u128),
    #[error("unknown bits: {0:#x}")]
    Unknown(u128),
    #[error("unknown flag name")]
    UnknownName,
    #[error(transparent)]
    ParseInt(#[from] ParseIntError),
}

/// Generates a bitflags-like struct with a fully `const` API.
///
/// Flags must be declared in bit-position order starting at 0, with contiguous
/// positions (this is checked at compile time). The underlying type must be an
/// unsigned integer.
///
/// The expanding crate needs the nightly features used by the generated code:
/// `const_trait_impl`, `derive_const`, `const_cmp`, `const_clone`, `const_ops`,
/// `const_convert`, `const_destruct`, `const_iter`, `const_result_trait_fn`,
/// `iter_intersperse`, and `macro_metavar_expr`.
///
/// ```ignore
/// utils::const_bitflags! {
///     /// Docs for the flags type.
///     pub struct Flags(u8);
///     pub struct Iter;
///
///     A = 0,
///     B = 1,
/// }
/// ```
///
/// This generates:
/// - `None`, one constant per flag, and `All`, plus `NAMES` and `COUNT`
/// - the `const` set-operation API (`contains`, `union`, `insert`, `toggle`, …)
/// - the `from_bits` family and `from_position`
/// - `Debug`, `Display`, `FromStr` (`"A | B"` and `0x…` hex forms), `Default`,
///   `From<int>`, const bit operators, `IntoIterator`, `Extend`, `FromIterator`
/// - an iterator struct over set bit positions (the second declared struct)
#[macro_export]
macro_rules! const_bitflags {
    (
        $(#[$meta:meta])*
        $vis:vis struct $Name:ident($T:ty);

        $(#[$iter_meta:meta])*
        $iter_vis:vis struct $Iter:ident;

        $(
            $(#[$flag_meta:meta])*
            $Flag:ident = $position:expr
        ),+
        $(,)?
    ) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(Copy)]
        #[derive_const(PartialEq, Clone, Eq, PartialOrd, Ord)]
        $vis struct $Name($T);

        const _: () = {
            $(assert!(
                $position == ${index()},
                concat!("flag `", stringify!($Flag), "` must be declared in bit-position order"),
            );)+
        };

        #[allow(non_upper_case_globals)]
        impl $Name {
            /// The name of every flag, indexed by bit position.
            $vis const NAMES: &'static [&'static str] = &[$(stringify!($Flag)),+];

            /// The number of flags defined on [`Self`].
            $vis const COUNT: usize = Self::NAMES.len();

            $vis const None: Self = Self(0);
            $(
                $(#[$flag_meta])*
                $vis const $Flag: Self = Self(1 << $position);
            )+
            $vis const All: Self = Self($((1 << $position))|+);

            /// Creates an empty set of flags.
            #[inline]
            $vis const fn empty() -> Self {
                Self::None
            }

            /// Creates a set of flags from bits.
            ///
            /// Equivalent to [`Self::from_bits_retained`].
            #[inline]
            $vis const fn new(bits: $T) -> Self {
                Self::from_bits_retained(bits)
            }

            #[inline]
            $vis const fn from_bits(bits: $T) -> Self {
                match Self::try_from_bits(bits) {
                    Ok(flags) => flags,
                    Err(_) => panic!("invalid bits"),
                }
            }

            #[inline]
            $vis const fn try_from_bits(bits: $T) -> Result<Self, $crate::ParseFlagsError> {
                if bits & !Self::All.into_inner() == 0 {
                    Ok(Self(bits))
                } else {
                    Err($crate::ParseFlagsError::Unknown(bits as u128))
                }
            }

            #[inline]
            $vis const fn from_bits_retained(bits: $T) -> Self {
                Self(bits)
            }

            #[inline]
            $vis const fn from_bits_truncated(bits: $T) -> Self {
                Self(bits & Self::All.into_inner())
            }

            #[inline]
            $vis const fn from_bits_unchecked(bits: $T) -> Self {
                Self(bits)
            }

            #[inline]
            $vis const fn from_bits_or_default(bits: $T) -> Self {
                Self::try_from_bits(bits).unwrap_or(Self::None)
            }

            #[inline]
            $vis const fn try_from_position(position: usize) -> Result<Self, $crate::ParseFlagsError> {
                if position >= Self::COUNT {
                    return Err($crate::ParseFlagsError::Invalid(position as u128));
                }
                Ok(Self(1 << position))
            }

            #[inline]
            $vis const fn from_position(position: usize) -> Self {
                match Self::try_from_position(position) {
                    Ok(flags) => flags,
                    Err(_) => panic!("invalid position"),
                }
            }

            #[inline]
            $vis const fn count_ones(self) -> u32 {
                self.0.count_ones()
            }

            #[inline]
            $vis const fn known(self) -> Self {
                Self(self.0 & Self::All.into_inner())
            }

            #[inline]
            $vis const fn unknown(self) -> Self {
                Self(self.0 & !Self::All.into_inner())
            }

            #[inline]
            $vis const fn has_unknown_bits(self) -> bool {
                self.unknown() != Self::None
            }

            #[inline]
            $vis const fn is_empty(self) -> bool {
                self.0 == 0
            }

            #[inline]
            $vis const fn is_all(self) -> bool {
                self.0 == Self::All.into_inner()
            }

            #[inline]
            $vis const fn equals(self, other: Self) -> bool {
                self.0 == other.0
            }

            #[inline]
            $vis const fn contains(self, other: Self) -> bool {
                self.0 & other.0 == other.0
            }

            #[inline]
            $vis const fn intersects(self, other: Self) -> bool {
                self.0 & other.0 != 0
            }

            #[inline]
            $vis const fn is_disjoint(self, other: Self) -> bool {
                self.0 & other.0 == 0
            }

            #[inline]
            #[must_use]
            $vis const fn union(self, other: Self) -> Self {
                Self(self.0 | other.0)
            }

            #[inline]
            #[must_use]
            $vis const fn intersection(self, other: Self) -> Self {
                Self(self.0 & other.0)
            }

            #[inline]
            #[must_use]
            $vis const fn difference(self, other: Self) -> Self {
                Self(self.0 & !other.0)
            }

            #[inline]
            #[must_use]
            $vis const fn symmetric_difference(self, other: Self) -> Self {
                Self((self.0 ^ other.0) & Self::All.into_inner())
            }

            #[inline]
            #[must_use]
            $vis const fn complement(self) -> Self {
                Self(!self.0 & Self::All.into_inner())
            }

            #[inline]
            $vis const fn insert(&mut self, other: Self) {
                self.0 |= other.0;
            }

            #[inline]
            $vis const fn remove(&mut self, other: Self) {
                self.0 &= !other.0;
            }

            #[inline]
            $vis const fn toggle(&mut self, other: Self) {
                self.0 = (self.0 ^ other.0) & Self::All.into_inner();
            }

            #[inline]
            $vis const fn clear(&mut self) {
                self.0 = 0;
            }

            /// Returns the number of known flags set.
            #[inline]
            $vis const fn count(self) -> usize {
                self.known().count_ones() as usize
            }

            /// Returns an iterator over the bit positions of the set flags.
            #[inline]
            $vis const fn iter(self) -> $Iter {
                $Iter::new(self.into_inner())
            }

            /// Returns an iterator over the names of the set flags.
            #[inline]
            $vis const fn names(self) -> impl Iterator<Item = &'static str> {
                self.iter().map(|i| Self::NAMES[i])
            }

            #[inline]
            $vis const fn into_inner(self) -> $T {
                self.0
            }

            /// Returns a `" | "`-separated string of the set flag names.
            $vis fn to_string(&self) -> ::std::borrow::Cow<'_, str> {
                self.names().intersperse(" | ").collect()
            }
        }

        impl ::std::fmt::Debug for $Name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                if self.is_empty() {
                    return f.write_str(concat!(stringify!($Name), "::None"));
                }

                f.debug_tuple(stringify!($Name))
                    .field(&::std::fmt::from_fn(|f| ::std::fmt::Display::fmt(self, f)))
                    .finish()
            }
        }
        impl ::std::fmt::Display for $Name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(self.to_string().as_ref())
            }
        }
        impl ::std::str::FromStr for $Name {
            type Err = $crate::ParseFlagsError;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                let s = s.trim();

                if s.is_empty() || s == "None" {
                    return Ok(Self::None);
                }

                let mut out = Self::empty();

                for part in s
                    .split('|')
                    .map(str::trim)
                    .filter(|s| !s.is_empty() && *s != "None")
                {
                    let flag = if let Some(hex) =
                        part.strip_prefix("0x").or_else(|| part.strip_prefix("0X"))
                    {
                        let bits = <$T>::from_str_radix(hex, 16)
                            .map_err($crate::ParseFlagsError::ParseInt)?;

                        Self::try_from_bits(bits)?
                    } else {
                        match Self::NAMES.iter().position(|name| *name == part) {
                            Some(position) => Self::from_position(position),
                            None => return Err($crate::ParseFlagsError::UnknownName),
                        }
                    };

                    out.insert(flag);
                }

                Ok(out)
            }
        }
        const impl ::std::convert::From<$T> for $Name {
            #[inline]
            fn from(value: $T) -> Self {
                Self::new(value)
            }
        }
        const impl ::std::default::Default for $Name {
            #[inline]
            fn default() -> Self {
                Self::None
            }
        }
        const impl ::std::ops::BitOr for $Name {
            type Output = Self;

            #[inline]
            fn bitor(self, rhs: Self) -> Self {
                self.union(rhs)
            }
        }
        impl ::std::ops::BitOrAssign for $Name {
            #[inline]
            fn bitor_assign(&mut self, rhs: Self) {
                self.insert(rhs);
            }
        }
        const impl ::std::ops::BitAnd for $Name {
            type Output = Self;

            #[inline]
            fn bitand(self, rhs: Self) -> Self {
                self.intersection(rhs)
            }
        }
        const impl ::std::ops::BitAndAssign for $Name {
            #[inline]
            fn bitand_assign(&mut self, rhs: Self) {
                *self = self.intersection(rhs);
            }
        }
        const impl ::std::ops::BitXor for $Name {
            type Output = Self;

            #[inline]
            fn bitxor(self, rhs: Self) -> Self {
                self.symmetric_difference(rhs)
            }
        }
        const impl ::std::ops::BitXorAssign for $Name {
            #[inline]
            fn bitxor_assign(&mut self, rhs: Self) {
                *self = self.symmetric_difference(rhs);
            }
        }
        const impl ::std::ops::Sub for $Name {
            type Output = Self;

            #[inline]
            fn sub(self, rhs: Self) -> Self {
                self.difference(rhs)
            }
        }
        const impl ::std::ops::SubAssign for $Name {
            #[inline]
            fn sub_assign(&mut self, rhs: Self) {
                self.remove(rhs);
            }
        }
        const impl ::std::ops::Not for $Name {
            type Output = Self;

            #[inline]
            fn not(self) -> Self {
                self.complement()
            }
        }
        const impl ::std::iter::IntoIterator for $Name {
            type Item = $Name;
            type IntoIter = ::std::iter::Map<$Iter, fn(usize) -> $Name>;

            #[inline]
            fn into_iter(self) -> Self::IntoIter {
                self.iter().map(Self::from_position)
            }
        }
        impl ::std::iter::Extend<$Name> for $Name {
            fn extend<T: IntoIterator<Item = $Name>>(&mut self, iter: T) {
                for flag in iter {
                    self.insert(flag);
                }
            }
        }
        impl ::std::iter::FromIterator<$Name> for $Name {
            fn from_iter<T: IntoIterator<Item = $Name>>(iter: T) -> Self {
                let mut out = Self::None;
                out.extend(iter);
                out
            }
        }

        $(#[$iter_meta])*
        /// Iterator over the bit positions set in the underlying value,
        /// lowest bit first.
        #[derive(Debug, Clone)]
        #[repr(transparent)]
        $iter_vis struct $Iter($T);

        const impl $Iter {
            #[inline]
            $iter_vis fn new(value: $T) -> Self {
                Self(value)
            }

            #[inline]
            fn lowest_bit(&self) -> usize {
                self.0.trailing_zeros() as usize
            }

            #[inline]
            fn highest_bit(&self) -> usize {
                (<$T>::BITS - 1 - self.0.leading_zeros()) as usize
            }

            #[inline]
            fn count_ones(&self) -> usize {
                self.0.count_ones() as usize
            }

            #[inline]
            fn clear_lowest(&mut self) {
                self.0 &= self.0.wrapping_sub(1);
            }
        }

        const impl ::std::iter::Iterator for $Iter {
            type Item = usize;

            fn next(&mut self) -> Option<Self::Item> {
                if self.0 != 0 {
                    let position = self.lowest_bit();
                    self.clear_lowest();
                    Some(position)
                } else {
                    None
                }
            }

            #[inline]
            fn size_hint(&self) -> (usize, Option<usize>) {
                let sz = self.count_ones();
                (sz, Some(sz))
            }

            #[inline]
            fn count(self) -> usize {
                self.count_ones()
            }

            #[inline]
            fn last(self) -> Option<Self::Item> {
                if self.0 != 0 {
                    Some(self.highest_bit())
                } else {
                    None
                }
            }

            #[inline]
            fn nth(&mut self, n: usize) -> Option<Self::Item> {
                let mut i = 0;
                while self.0 != 0 && i < n {
                    self.clear_lowest();
                    i += 1;
                }
                self.next()
            }

            #[inline]
            fn fold<B, F>(mut self, init: B, mut f: F) -> B
            where
                F: [const] FnMut(B, Self::Item) -> B + [const] ::std::marker::Destruct,
            {
                let mut accum = init;
                while self.0 != 0 {
                    accum = f(accum, self.lowest_bit());
                    self.clear_lowest();
                }
                accum
            }

            #[inline]
            fn max(self) -> Option<Self::Item> {
                self.last()
            }

            #[inline]
            fn min(mut self) -> Option<Self::Item> {
                self.next()
            }

            fn is_sorted(self) -> bool {
                true
            }
        }
        impl ::std::iter::ExactSizeIterator for $Iter {
            fn len(&self) -> usize {
                self.count_ones()
            }
        }
    };
}
