
#[derive(Clone, Copy, Eq, PartialEq, Default, Hash, Debug)]
pub enum Color2 {
    Black,
    Red,
    Green,
    Yellow,
    Blue,
    Magenta,
    Cyan,
    White,
    BrightBlack,
    BrightRed,
    BrightGreen,
    BrightYellow,
    BrightBlue,
    BrightMagenta,
    BrightCyan,
    BrightWhite,
    ExtendedBlack,
    StratosBlue,
    NavyBlue,
    MidnightBlue,
    DarkBlue,
    ExtendedBlue,
    CamaroneGreen,
    BlueStone,
    OrientBlue,
    EndeavourBlue,
    ScienceBlue,
    BlueRibbon,
    JapaneseLaurel,
    DeepSeaGreen,
    Teal,
    DeepCerulean,
    LochmaraBlue,
    AzureRadiance,
    LightJapaneseLaurel,
    Jade,
    PersianGreen,
    BondiBlue,
    Cerulean,
    LightAzureRadiance,
    DarkGreen,
    Malachite,
    CaribbeanGreen,
    LightCaribbeanGreen,
    RobinEggBlue,
    Aqua,
    ExtendedGreen,
    DarkSpringGreen,
    SpringGreen,
    LightSpringGreen,
    BrightTurquoise,
    ExtendedCyan,
    Rosewood,
    PompadourMagenta,
    PigmentIndigo,
    DarkPurple,
    ElectricIndigo,
    ElectricPurple,
    VerdunGreen,
    ScorpionOlive,
    Lilac,
    ScampiIndigo,
    Indigo,
    DarkCornflowerBlue,
    DarkLimeade,
    GladeGreen,
    JuniperGreen,
    HippieBlue,
    HavelockBlue,
    CornflowerBlue,
    Limeade,
    FernGreen,
    SilverTree,
    Tradewind,
    ShakespeareBlue,
    DarkMalibuBlue,
    DarkBrightGreen,
    DarkPastelGreen,
    PastelGreen,
    DownyTeal,
    Viking,
    MalibuBlue,
    ExtendedBrightGreen,
    DarkScreaminGreen,
    ScreaminGreen,
    DarkAquamarine,
    Aquamarine,
    LightAquamarine,
    Maroon,
    DarkFreshEggplant,
    LightFreshEggplant,
    Purple,
    ElectricViolet,
    LightElectricViolet,
    Brown,
    CopperRose,
    StrikemasterPurple,
    DelugePurple,
    DarkMediumPurple,
    DarkHeliotropePurple,
    Olive,
    ClayCreekOlive,
    DarkGray,
    WildBlueYonder,
    ChetwodeBlue,
    SlateBlue,
    LightLimeade,
    ChelseaCucumber,
    BayLeaf,
    GulfStream,
    PoloBlue,
    LightMalibuBlue,
    Pistachio,
    LightPastelGreen,
    DarkFeijoaGreen,
    VistaBlue,
    Bermuda,
    DarkAnakiwaBlue,
    ChartreuseGreen,
    LightScreaminGreen,
    DarkMintGreen,
    MintGreen,
    LighterAquamarine,
    AnakiwaBlue,
    ExtendedBrightRed,
    DarkFlirt,
    Flirt,
    LightFlirt,
    DarkViolet,
    BrightElectricViolet,
    RoseofSharonOrange,
    MatrixPink,
    TapestryPink,
    FuchsiaPink,
    MediumPurple,
    Heliotrope,
    PirateGold,
    MuesliOrange,
    PharlapPink,
    Bouquet,
    Lavender,
    LightHeliotrope,
    BuddhaGold,
    OliveGreen,
    HillaryOlive,
    SilverChalice,
    WistfulLilac,
    MelroseLilac,
    RioGrandeGreen,
    ConiferGreen,
    Feijoa,
    PixieGreen,
    JungleMist,
    LightAnakiwaBlue,
    Lime,
    GreenYellow,
    LightMintGreen,
    Celadon,
    AeroBlue,
    FrenchPassLightBlue,
    GuardsmanRed,
    RazzmatazzCerise,
    MediumVioletRed,
    HollywoodCerise,
    DarkPurplePizzazz,
    BrighterElectricViolet,
    TennOrange,
    RomanOrange,
    CranberryPink,
    HopbushPink,
    Orchid,
    LighterHeliotrope,
    MangoTango,
    Copperfield,
    SeaPink,
    CanCanPink,
    LightOrchid,
    BrightHeliotrope,
    DarkCorn,
    DarkTachaOrange,
    TanBeige,
    ClamShell,
    ThistlePink,
    Mauve,
    Corn,
    TachaOrange,
    DecoOrange,
    PaleGoldenrod,
    AltoBeige,
    FogPink,
    ChartreuseYellow,
    Canary,
    Honeysuckle,
    ReefPaleYellow,
    SnowyMint,
    OysterBay,
    ExtendedRed,
    DarkRose,
    Rose,
    LightHollywoodCerise,
    PurplePizzazz,
    Fuchsia,
    BlazeOrange,
    BittersweetOrange,
    WildWatermelon,
    DarkHotPink,
    HotPink,
    PinkFlamingo,
    FlushOrange,
    Salmon,
    VividTangerine,
    PinkSalmon,
    DarkLavenderRose,
    BlushPink,
    YellowSea,
    TexasRose,
    Tacao,
    Sundown,
    CottonCandy,
    LavenderRose,
    Gold,
    Dandelion,
    GrandisCaramel,
    Caramel,
    CosmosSalmon,
    PinkLace,
    ExtendedYellow,
    LaserLemon,
    DollyYellow,
    PortafinoYellow,
    Cumulus,
    ExtendedWhite,
    DarkCodGray,
    CodGray,
    LightCodGray,
    DarkMineShaft,
    MineShaft,
    LightMineShaft,
    DarkTundora,
    Tundora,
    ScorpionGray,
    DarkDoveGray,
    DoveGray,
    Boulder,
    Gray,
    LightGray,
    DustyGray,
    NobelGray,
    DarkSilverChalice,
    LightSilverChalice,
    DarkSilver,
    Silver,
    DarkAlto,
    Alto,
    Mercury,
    GalleryGray,

    Index(u8),
    Rgb(u8, u8, u8),

    #[default]
    Default,

    None,
}


use modular_bitfield::prelude::*;

#[derive(Specifier)]
#[bits = 2]
enum ColorKindBits {
    None,
    Default,
    Index,
    Rgb,
}

#[bitfield]
#[derive(Specifier)]
#[repr(u32)]
struct RgbBits {
    #[skip]
    _reserved: B8,
    r: B8,
    g: B8,
    b: B8,
}

#[bitfield]
#[derive(Specifier)]
#[repr(u32)]
struct ColorBits {
    #[skip]
    _reserved: B6,
    tag: ColorKindBits,
    value: B24,
}

#[bitfield]
#[derive(Specifier)]
#[repr(u64)]
struct BitColors {
    foreground: ColorBits,
    background: ColorBits,
}

/*use crate::{Color, ColorSpace};
use bilge::prelude::*;
use utils::{Unpack, Pack};

#[bitsize(32)]
#[derive(DefaultBits, FromBits)]
struct ColorBits {
    space: ColorSpace,
    value: u30,
}

impl Unpack<ColorBits> for Color {
    #[inline]
    fn unpack(packed: ColorBits) -> Self {
        match packed.space() {
            ColorSpace::None => Color::None,
            ColorSpace::Default => Color::Default,
            ColorSpace::Ansi => Color::Index(packed.value().as_u8()),
            ColorSpace::Rgb => {
                let value = packed.value.as_u8();
                Color::Rgb((value >> 16) as u8, (value >> 8) as u8, value as u8)
            }
        }
    }
}

impl Pack<ColorBits> for Color {
    #[inline]
    fn pack(self) -> ColorBits {
        match self {
            Color::None => ColorBits::new(ColorSpace::None, u30::ZERO),
            Color::Default => ColorBits::new(ColorSpace::Default, u30::ZERO),
            Color::Black => ColorBits::new(ColorSpace::Ansi, u30::new(0)),
            Color::Red => ColorBits::new(ColorSpace::Ansi, u30::new(1)),
            Color::Green => ColorBits::new(ColorSpace::Ansi, u30::new(2)),
            Color::Yellow => ColorBits::new(ColorSpace::Ansi, u30::new(3)),
            Color::Blue => ColorBits::new(ColorSpace::Ansi, u30::new(4)),
            Color::Magenta => ColorBits::new(ColorSpace::Ansi, u30::new(5)),
            Color::Cyan => ColorBits::new(ColorSpace::Ansi, u30::new(6)),
            Color::White => ColorBits::new(ColorSpace::Ansi, u30::new(7)),
            Color::BrightBlack => ColorBits::new(ColorSpace::Ansi, u30::new(8)),
            Color::BrightRed => ColorBits::new(ColorSpace::Ansi, u30::new(9)),
            Color::BrightGreen => ColorBits::new(ColorSpace::Ansi, u30::new(10)),
            Color::BrightYellow => ColorBits::new(ColorSpace::Ansi, u30::new(11)),
            Color::BrightBlue => ColorBits::new(ColorSpace::Ansi, u30::new(12)),
            Color::BrightMagenta => ColorBits::new(ColorSpace::Ansi, u30::new(13)),
            Color::BrightCyan => ColorBits::new(ColorSpace::Ansi, u30::new(14)),
            Color::BrightWhite => ColorBits::new(ColorSpace::Ansi, u30::new(15)),
            Color::Index(index) => ColorBits::new(ColorSpace::Ansi, u30::from(index)),
            Color::Rgb(r, g, b) => ColorBits::new(
                ColorSpace::Rgb,
                u30::new(((r as u32) << 16) | ((g as u32) << 8) | (b as u32)),
            ),
        }

    }
}
*/