// Source: https://unicode-explorer.com/blocks

// Box drawing

/// U+2500: BOX DRAWINGS LIGHT HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_HORIZONTAL: &str = "─";

/// U+2501: BOX DRAWINGS HEAVY HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_HORIZONTAL: &str = "━";

/// U+2502: BOX DRAWINGS LIGHT VERTICAL
pub const BOX_DRAWINGS_LIGHT_VERTICAL: &str = "│";

/// U+2503: BOX DRAWINGS HEAVY VERTICAL
pub const BOX_DRAWINGS_HEAVY_VERTICAL: &str = "┃";

/// U+2504: BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_TRIPLE_DASH_HORIZONTAL: &str = "┄";

/// U+2505: BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_TRIPLE_DASH_HORIZONTAL: &str = "┅";

/// U+2506: BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL
pub const BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL: &str = "┆";

/// U+2507: BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL
pub const BOX_DRAWINGS_HEAVY_TRIPLE_DASH_VERTICAL: &str = "┇";

/// U+2508: BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL: &str = "┈";

/// U+2509: BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_HORIZONTAL: &str = "┉";

/// U+250A: BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL
pub const BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_VERTICAL: &str = "┊";

/// U+250B: BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL
pub const BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_VERTICAL: &str = "┋";

/// U+250C: BOX DRAWINGS LIGHT DOWN AND RIGHT
pub const BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT: &str = "┌";

/// U+250D: BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY
pub const BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_HEAVY: &str = "┍";

/// U+250E: BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT
pub const BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_LIGHT: &str = "┎";

/// U+250F: BOX DRAWINGS HEAVY DOWN AND RIGHT
pub const BOX_DRAWINGS_HEAVY_DOWN_AND_RIGHT: &str = "┏";

/// U+2510: BOX DRAWINGS LIGHT DOWN AND LEFT
pub const BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT: &str = "┐";

/// U+2511: BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY
pub const BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_HEAVY: &str = "┑";

/// U+2512: BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT
pub const BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_LIGHT: &str = "┒";

/// U+2513: BOX DRAWINGS HEAVY DOWN AND LEFT
pub const BOX_DRAWINGS_HEAVY_DOWN_AND_LEFT: &str = "┓";

/// U+2514: BOX DRAWINGS LIGHT UP AND RIGHT
pub const BOX_DRAWINGS_LIGHT_UP_AND_RIGHT: &str = "└";

/// U+2515: BOX DRAWINGS UP LIGHT AND RIGHT HEAVY
pub const BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_HEAVY: &str = "┕";

/// U+2516: BOX DRAWINGS UP HEAVY AND RIGHT LIGHT
pub const BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_LIGHT: &str = "┖";

/// U+2517: BOX DRAWINGS HEAVY UP AND RIGHT
pub const BOX_DRAWINGS_HEAVY_UP_AND_RIGHT: &str = "┗";

/// U+2518: BOX DRAWINGS LIGHT UP AND LEFT
pub const BOX_DRAWINGS_LIGHT_UP_AND_LEFT: &str = "┘";

/// U+2519: BOX DRAWINGS UP LIGHT AND LEFT HEAVY
pub const BOX_DRAWINGS_UP_LIGHT_AND_LEFT_HEAVY: &str = "┙";

/// U+251A: BOX DRAWINGS UP HEAVY AND LEFT LIGHT
pub const BOX_DRAWINGS_UP_HEAVY_AND_LEFT_LIGHT: &str = "┚";

/// U+251B: BOX DRAWINGS HEAVY UP AND LEFT
pub const BOX_DRAWINGS_HEAVY_UP_AND_LEFT: &str = "┛";

/// U+251C: BOX DRAWINGS LIGHT VERTICAL AND RIGHT
pub const BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT: &str = "├";

/// U+251D: BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY
pub const BOX_DRAWINGS_VERTICAL_LIGHT_AND_RIGHT_HEAVY: &str = "┝";

/// U+251E: BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT
pub const BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_DOWN_LIGHT: &str = "┞";

/// U+251F: BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT
pub const BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_UP_LIGHT: &str = "┟";

/// U+2520: BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT
pub const BOX_DRAWINGS_VERTICAL_HEAVY_AND_RIGHT_LIGHT: &str = "┠";

/// U+2521: BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY
pub const BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_UP_HEAVY: &str = "┡";

/// U+2522: BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY
pub const BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_DOWN_HEAVY: &str = "┢";

/// U+2523: BOX DRAWINGS HEAVY VERTICAL AND RIGHT
pub const BOX_DRAWINGS_HEAVY_VERTICAL_AND_RIGHT: &str = "┣";

/// U+2524: BOX DRAWINGS LIGHT VERTICAL AND LEFT
pub const BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT: &str = "┤";

/// U+2525: BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY
pub const BOX_DRAWINGS_VERTICAL_LIGHT_AND_LEFT_HEAVY: &str = "┥";

/// U+2526: BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT
pub const BOX_DRAWINGS_UP_HEAVY_AND_LEFT_DOWN_LIGHT: &str = "┦";

/// U+2527: BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT
pub const BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_UP_LIGHT: &str = "┧";

/// U+2528: BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT
pub const BOX_DRAWINGS_VERTICAL_HEAVY_AND_LEFT_LIGHT: &str = "┨";

/// U+2529: BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY
pub const BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_UP_HEAVY: &str = "┩";

/// U+252A: BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY
pub const BOX_DRAWINGS_UP_LIGHT_AND_LEFT_DOWN_HEAVY: &str = "┪";

/// U+252B: BOX DRAWINGS HEAVY VERTICAL AND LEFT
pub const BOX_DRAWINGS_HEAVY_VERTICAL_AND_LEFT: &str = "┫";

/// U+252C: BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL: &str = "┬";

/// U+252D: BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT
pub const BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT: &str = "┭";

/// U+252E: BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT
pub const BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT: &str = "┮";

/// U+252F: BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY
pub const BOX_DRAWINGS_DOWN_LIGHT_AND_HORIZONTAL_HEAVY: &str = "┯";

/// U+2530: BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT
pub const BOX_DRAWINGS_DOWN_HEAVY_AND_HORIZONTAL_LIGHT: &str = "┰";

/// U+2531: BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY
pub const BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY: &str = "┱";

/// U+2532: BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY
pub const BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY: &str = "┲";

/// U+2533: BOX DRAWINGS HEAVY DOWN AND HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_DOWN_AND_HORIZONTAL: &str = "┳";

/// U+2534: BOX DRAWINGS LIGHT UP AND HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL: &str = "┴";

/// U+2535: BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT
pub const BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_UP_LIGHT: &str = "┵";

/// U+2536: BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT
pub const BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_UP_LIGHT: &str = "┶";

/// U+2537: BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY
pub const BOX_DRAWINGS_UP_LIGHT_AND_HORIZONTAL_HEAVY: &str = "┷";

/// U+2538: BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT
pub const BOX_DRAWINGS_UP_HEAVY_AND_HORIZONTAL_LIGHT: &str = "┸";

/// U+2539: BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY
pub const BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_UP_HEAVY: &str = "┹";

/// U+253A: BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY
pub const BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_UP_HEAVY: &str = "┺";

/// U+253B: BOX DRAWINGS HEAVY UP AND HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_UP_AND_HORIZONTAL: &str = "┻";

/// U+253C: BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL: &str = "┼";

/// U+253D: BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT
pub const BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT: &str = "┽";

/// U+253E: BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT
pub const BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT: &str = "┾";

/// U+253F: BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY
pub const BOX_DRAWINGS_VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY: &str = "┿";

/// U+2540: BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT
pub const BOX_DRAWINGS_UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT: &str = "╀";

/// U+2541: BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT
pub const BOX_DRAWINGS_DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT: &str = "╁";

/// U+2542: BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT
pub const BOX_DRAWINGS_VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT: &str = "╂";

/// U+2543: BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT
pub const BOX_DRAWINGS_LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT: &str = "╃";

/// U+2544: BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT
pub const BOX_DRAWINGS_RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT: &str = "╄";

/// U+2545: BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT
pub const BOX_DRAWINGS_LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT: &str = "╅";

/// U+2546: BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT
pub const BOX_DRAWINGS_RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT: &str = "╆";

/// U+2547: BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY
pub const BOX_DRAWINGS_DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY: &str = "╇";

/// U+2548: BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY
pub const BOX_DRAWINGS_UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY: &str = "╈";

/// U+2549: BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY
pub const BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY: &str = "╉";

/// U+254A: BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY
pub const BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY: &str = "╊";

/// U+254B: BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_VERTICAL_AND_HORIZONTAL: &str = "╋";

/// U+254C: BOX DRAWINGS LIGHT DOUBLE DASH HORIZONTAL
pub const BOX_DRAWINGS_LIGHT_DOUBLE_DASH_HORIZONTAL: &str = "╌";

/// U+254D: BOX DRAWINGS HEAVY DOUBLE DASH HORIZONTAL
pub const BOX_DRAWINGS_HEAVY_DOUBLE_DASH_HORIZONTAL: &str = "╍";

/// U+254E: BOX DRAWINGS LIGHT DOUBLE DASH VERTICAL
pub const BOX_DRAWINGS_LIGHT_DOUBLE_DASH_VERTICAL: &str = "╎";

/// U+254F: BOX DRAWINGS HEAVY DOUBLE DASH VERTICAL
pub const BOX_DRAWINGS_HEAVY_DOUBLE_DASH_VERTICAL: &str = "╏";

/// U+2550: BOX DRAWINGS DOUBLE HORIZONTAL
pub const BOX_DRAWINGS_DOUBLE_HORIZONTAL: &str = "═";

/// U+2551: BOX DRAWINGS DOUBLE VERTICAL
pub const BOX_DRAWINGS_DOUBLE_VERTICAL: &str = "║";

/// U+2552: BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
pub const BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE: &str = "╒";

/// U+2553: BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
pub const BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE: &str = "╓";

/// U+2554: BOX DRAWINGS DOUBLE DOWN AND RIGHT
pub const BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT: &str = "╔";

/// U+2555: BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
pub const BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE: &str = "╕";

/// U+2556: BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
pub const BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE: &str = "╖";

/// U+2557: BOX DRAWINGS DOUBLE DOWN AND LEFT
pub const BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT: &str = "╗";

/// U+2558: BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
pub const BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE: &str = "╘";

/// U+2559: BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
pub const BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE: &str = "╙";

/// U+255A: BOX DRAWINGS DOUBLE UP AND RIGHT
pub const BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT: &str = "╚";

/// U+255B: BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
pub const BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE: &str = "╛";

/// U+255C: BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
pub const BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE: &str = "╜";

/// U+255D: BOX DRAWINGS DOUBLE UP AND LEFT
pub const BOX_DRAWINGS_DOUBLE_UP_AND_LEFT: &str = "╝";

/// U+255E: BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
pub const BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE: &str = "╞";

/// U+255F: BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
pub const BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE: &str = "╟";

/// U+2560: BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
pub const BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT: &str = "╠";

/// U+2561: BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
pub const BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE: &str = "╡";

/// U+2562: BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
pub const BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE: &str = "╢";

/// U+2563: BOX DRAWINGS DOUBLE VERTICAL AND LEFT
pub const BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT: &str = "╣";

/// U+2564: BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
pub const BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE: &str = "╤";

/// U+2565: BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
pub const BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE: &str = "╥";

/// U+2566: BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
pub const BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL: &str = "╦";

/// U+2567: BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
pub const BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE: &str = "╧";

/// U+2568: BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
pub const BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE: &str = "╨";

/// U+2569: BOX DRAWINGS DOUBLE UP AND HORIZONTAL
pub const BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL: &str = "╩";

/// U+256A: BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
pub const BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE: &str = "╪";

/// U+256B: BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
pub const BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE: &str = "╫";

/// U+256C: BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
pub const BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL: &str = "╬";

/// U+256D: BOX DRAWINGS LIGHT ARC DOWN AND RIGHT
pub const BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_RIGHT: &str = "╭";

/// U+256E: BOX DRAWINGS LIGHT ARC DOWN AND LEFT
pub const BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_LEFT: &str = "╮";

/// U+256F: BOX DRAWINGS LIGHT ARC UP AND LEFT
pub const BOX_DRAWINGS_LIGHT_ARC_UP_AND_LEFT: &str = "╯";

/// U+2570: BOX DRAWINGS LIGHT ARC UP AND RIGHT
pub const BOX_DRAWINGS_LIGHT_ARC_UP_AND_RIGHT: &str = "╰";

/// U+2571: BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT: &str = "╱";

/// U+2572: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT: &str = "╲";

/// U+2573: BOX DRAWINGS LIGHT DIAGONAL CROSS
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_CROSS: &str = "╳";

/// U+2574: BOX DRAWINGS LIGHT LEFT
pub const BOX_DRAWINGS_LIGHT_LEFT: &str = "╴";

/// U+2575: BOX DRAWINGS LIGHT UP
pub const BOX_DRAWINGS_LIGHT_UP: &str = "╵";

/// U+2576: BOX DRAWINGS LIGHT RIGHT
pub const BOX_DRAWINGS_LIGHT_RIGHT: &str = "╶";

/// U+2577: BOX DRAWINGS LIGHT DOWN
pub const BOX_DRAWINGS_LIGHT_DOWN: &str = "╷";

/// U+2578: BOX DRAWINGS HEAVY LEFT
pub const BOX_DRAWINGS_HEAVY_LEFT: &str = "╸";

/// U+2579: BOX DRAWINGS HEAVY UP
pub const BOX_DRAWINGS_HEAVY_UP: &str = "╹";

/// U+257A: BOX DRAWINGS HEAVY RIGHT
pub const BOX_DRAWINGS_HEAVY_RIGHT: &str = "╺";

/// U+257B: BOX DRAWINGS HEAVY DOWN
pub const BOX_DRAWINGS_HEAVY_DOWN: &str = "╻";

/// U+257C: BOX DRAWINGS LIGHT LEFT AND HEAVY RIGHT
pub const BOX_DRAWINGS_LIGHT_LEFT_AND_HEAVY_RIGHT: &str = "╼";

/// U+257D: BOX DRAWINGS LIGHT UP AND HEAVY DOWN
pub const BOX_DRAWINGS_LIGHT_UP_AND_HEAVY_DOWN: &str = "╽";

/// U+257E: BOX DRAWINGS HEAVY LEFT AND LIGHT RIGHT
pub const BOX_DRAWINGS_HEAVY_LEFT_AND_LIGHT_RIGHT: &str = "╾";

/// U+257F: BOX DRAWINGS HEAVY UP AND LIGHT DOWN
pub const BOX_DRAWINGS_HEAVY_UP_AND_LIGHT_DOWN: &str = "╿";

// Block elements

/// U+2580: UPPER HALF BLOCK
pub const UPPER_HALF_BLOCK: &str = "▀";

/// U+2581: LOWER ONE EIGHTH BLOCK
pub const LOWER_ONE_EIGHTH_BLOCK: &str = "▁";

/// U+2582: LOWER ONE QUARTER BLOCK
pub const LOWER_ONE_QUARTER_BLOCK: &str = "▂";

/// U+2583: LOWER THREE EIGHTHS BLOCK
pub const LOWER_THREE_EIGHTHS_BLOCK: &str = "▃";

/// U+2584: LOWER HALF BLOCK
pub const LOWER_HALF_BLOCK: &str = "▄";

/// U+2585: LOWER FIVE EIGHTHS BLOCK
pub const LOWER_FIVE_EIGHTHS_BLOCK: &str = "▅";

/// U+2586: LOWER THREE QUARTERS BLOCK
pub const LOWER_THREE_QUARTERS_BLOCK: &str = "▆";

/// U+2587: LOWER SEVEN EIGHTHS BLOCK
pub const LOWER_SEVEN_EIGHTHS_BLOCK: &str = "▇";

/// U+2588: FULL BLOCK
pub const FULL_BLOCK: &str = "█";

/// U+2589: LEFT SEVEN EIGHTHS BLOCK
pub const LEFT_SEVEN_EIGHTHS_BLOCK: &str = "▉";

/// U+258A: LEFT THREE QUARTERS BLOCK
pub const LEFT_THREE_QUARTERS_BLOCK: &str = "▊";

/// U+258B: LEFT FIVE EIGHTHS BLOCK
pub const LEFT_FIVE_EIGHTHS_BLOCK: &str = "▋";

/// U+258C: LEFT HALF BLOCK
pub const LEFT_HALF_BLOCK: &str = "▌";

/// U+258D: LEFT THREE EIGHTHS BLOCK
pub const LEFT_THREE_EIGHTHS_BLOCK: &str = "▍";

/// U+258E: LEFT ONE QUARTER BLOCK
pub const LEFT_ONE_QUARTER_BLOCK: &str = "▎";

/// U+258F: LEFT ONE EIGHTH BLOCK
pub const LEFT_ONE_EIGHTH_BLOCK: &str = "▏";

/// U+2590: RIGHT HALF BLOCK
pub const RIGHT_HALF_BLOCK: &str = "▐";

/// U+2591: LIGHT SHADE
pub const LIGHT_SHADE: &str = "░";

/// U+2592: MEDIUM SHADE
pub const MEDIUM_SHADE: &str = "▒";

/// U+2593: DARK SHADE
pub const DARK_SHADE: &str = "▓";

/// U+2594: UPPER ONE EIGHTH BLOCK
pub const UPPER_ONE_EIGHTH_BLOCK: &str = "▔";

/// U+2595: RIGHT ONE EIGHTH BLOCK
pub const RIGHT_ONE_EIGHTH_BLOCK: &str = "▕";

/// U+2596: QUADRANT LOWER LEFT
pub const QUADRANT_LOWER_LEFT: &str = "▖";

/// U+2597: QUADRANT LOWER RIGHT
pub const QUADRANT_LOWER_RIGHT: &str = "▗";

/// U+2598: QUADRANT UPPER LEFT
pub const QUADRANT_UPPER_LEFT: &str = "▘";

/// U+2599: QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT
pub const QUADRANT_UPPER_LEFT_AND_LOWER_LEFT_AND_LOWER_RIGHT: &str = "▙";

/// U+259A: QUADRANT UPPER LEFT AND LOWER RIGHT
pub const QUADRANT_UPPER_LEFT_AND_LOWER_RIGHT: &str = "▚";

/// U+259B: QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT
pub const QUADRANT_UPPER_LEFT_AND_UPPER_RIGHT_AND_LOWER_LEFT: &str = "▛";

/// U+259C: QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT
pub const QUADRANT_UPPER_LEFT_AND_UPPER_RIGHT_AND_LOWER_RIGHT: &str = "▜";

/// U+259D: QUADRANT UPPER RIGHT
pub const QUADRANT_UPPER_RIGHT: &str = "▝";

/// U+259E: QUADRANT UPPER RIGHT AND LOWER LEFT
pub const QUADRANT_UPPER_RIGHT_AND_LOWER_LEFT: &str = "▞";

/// U+259F: QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT
pub const QUADRANT_UPPER_RIGHT_AND_LOWER_LEFT_AND_LOWER_RIGHT: &str = "▟";

// Geometric shapes

/// U+25A0: BLACK SQUARE
pub const BLACK_SQUARE: &str = "■";

/// U+25A1: WHITE SQUARE
pub const WHITE_SQUARE: &str = "□";

/// U+25A2: WHITE SQUARE WITH ROUNDED CORNERS
pub const WHITE_SQUARE_WITH_ROUNDED_CORNERS: &str = "▢";

/// U+25A3: WHITE SQUARE CONTAINING BLACK SMALL SQUARE
pub const WHITE_SQUARE_CONTAINING_BLACK_SMALL_SQUARE: &str = "▣";

/// U+25A4: SQUARE WITH HORIZONTAL FILL
pub const SQUARE_WITH_HORIZONTAL_FILL: &str = "▤";

/// U+25A5: SQUARE WITH VERTICAL FILL
pub const SQUARE_WITH_VERTICAL_FILL: &str = "▥";

/// U+25A6: SQUARE WITH ORTHOGONAL CROSSHATCH FILL
pub const SQUARE_WITH_ORTHOGONAL_CROSSHATCH_FILL: &str = "▦";

/// U+25A7: SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL
pub const SQUARE_WITH_UPPER_LEFT_TO_LOWER_RIGHT_FILL: &str = "▧";

/// U+25A8: SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL
pub const SQUARE_WITH_UPPER_RIGHT_TO_LOWER_LEFT_FILL: &str = "▨";

/// U+25A9: SQUARE WITH DIAGONAL CROSSHATCH FILL
pub const SQUARE_WITH_DIAGONAL_CROSSHATCH_FILL: &str = "▩";

/// U+25AA: BLACK SMALL SQUARE
pub const BLACK_SMALL_SQUARE: &str = "▪";

/// U+25AB: WHITE SMALL SQUARE
pub const WHITE_SMALL_SQUARE: &str = "▫";

/// U+25AC: BLACK RECTANGLE
pub const BLACK_RECTANGLE: &str = "▬";

/// U+25AD: WHITE RECTANGLE
pub const WHITE_RECTANGLE: &str = "▭";

/// U+25AE: BLACK VERTICAL RECTANGLE
pub const BLACK_VERTICAL_RECTANGLE: &str = "▮";

/// U+25AF: WHITE VERTICAL RECTANGLE
pub const WHITE_VERTICAL_RECTANGLE: &str = "▯";

/// U+25B0: BLACK PARALLELOGRAM
pub const BLACK_PARALLELOGRAM: &str = "▰";

/// U+25B1: WHITE PARALLELOGRAM
pub const WHITE_PARALLELOGRAM: &str = "▱";

/// U+25B2: BLACK UP-POINTING TRIANGLE
pub const BLACK_UP_POINTING_TRIANGLE: &str = "▲";

/// U+25B3: WHITE UP-POINTING TRIANGLE
pub const WHITE_UP_POINTING_TRIANGLE: &str = "△";

/// U+25B4: BLACK UP-POINTING SMALL TRIANGLE
pub const BLACK_UP_POINTING_SMALL_TRIANGLE: &str = "▴";

/// U+25B5: WHITE UP-POINTING SMALL TRIANGLE
pub const WHITE_UP_POINTING_SMALL_TRIANGLE: &str = "▵";

/// U+25B6: BLACK RIGHT-POINTING TRIANGLE
pub const BLACK_RIGHT_POINTING_TRIANGLE: &str = "▶";

/// U+25B7: WHITE RIGHT-POINTING TRIANGLE
pub const WHITE_RIGHT_POINTING_TRIANGLE: &str = "▷";

/// U+25B8: BLACK RIGHT-POINTING SMALL TRIANGLE
pub const BLACK_RIGHT_POINTING_SMALL_TRIANGLE: &str = "▸";

/// U+25B9: WHITE RIGHT-POINTING SMALL TRIANGLE
pub const WHITE_RIGHT_POINTING_SMALL_TRIANGLE: &str = "▹";

/// U+25BA: BLACK RIGHT-POINTING POINTER
pub const BLACK_RIGHT_POINTING_POINTER: &str = "►";

/// U+25BB: WHITE RIGHT-POINTING POINTER
pub const WHITE_RIGHT_POINTING_POINTER: &str = "▻";

/// U+25BC: BLACK DOWN-POINTING TRIANGLE
pub const BLACK_DOWN_POINTING_TRIANGLE: &str = "▼";

/// U+25BD: WHITE DOWN-POINTING TRIANGLE
pub const WHITE_DOWN_POINTING_TRIANGLE: &str = "▽";

/// U+25BE: BLACK DOWN-POINTING SMALL TRIANGLE
pub const BLACK_DOWN_POINTING_SMALL_TRIANGLE: &str = "▾";

/// U+25BF: WHITE DOWN-POINTING SMALL TRIANGLE
pub const WHITE_DOWN_POINTING_SMALL_TRIANGLE: &str = "▿";

/// U+25C0: BLACK LEFT-POINTING TRIANGLE
pub const BLACK_LEFT_POINTING_TRIANGLE: &str = "◀";

/// U+25C1: WHITE LEFT-POINTING TRIANGLE
pub const WHITE_LEFT_POINTING_TRIANGLE: &str = "◁";

/// U+25C2: BLACK LEFT-POINTING SMALL TRIANGLE
pub const BLACK_LEFT_POINTING_SMALL_TRIANGLE: &str = "◂";

/// U+25C3: WHITE LEFT-POINTING SMALL TRIANGLE
pub const WHITE_LEFT_POINTING_SMALL_TRIANGLE: &str = "◃";

/// U+25C4: BLACK LEFT-POINTING POINTER
pub const BLACK_LEFT_POINTING_POINTER: &str = "◄";

/// U+25C5: WHITE LEFT-POINTING POINTER
pub const WHITE_LEFT_POINTING_POINTER: &str = "◅";

/// U+25C6: BLACK DIAMOND
pub const BLACK_DIAMOND: &str = "◆";

/// U+25C7: WHITE DIAMOND
pub const WHITE_DIAMOND: &str = "◇";

/// U+25C8: WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND
pub const WHITE_DIAMOND_CONTAINING_BLACK_SMALL_DIAMOND: &str = "◈";

/// U+25C9: FISHEYE
pub const FISHEYE: &str = "◉";

/// U+25CA: LOZENGE
pub const LOZENGE: &str = "◊";

/// U+25CB: WHITE CIRCLE
pub const WHITE_CIRCLE: &str = "○";

/// U+25CC: DOTTED CIRCLE
pub const DOTTED_CIRCLE: &str = "◌";

/// U+25CD: CIRCLE WITH VERTICAL FILL
pub const CIRCLE_WITH_VERTICAL_FILL: &str = "◍";

/// U+25CE: BULLSEYE
pub const BULLSEYE: &str = "◎";

/// U+25CF: BLACK CIRCLE
pub const BLACK_CIRCLE: &str = "●";

/// U+25D0: CIRCLE WITH LEFT HALF BLACK
pub const CIRCLE_WITH_LEFT_HALF_BLACK: &str = "◐";

/// U+25D1: CIRCLE WITH RIGHT HALF BLACK
pub const CIRCLE_WITH_RIGHT_HALF_BLACK: &str = "◑";

/// U+25D2: CIRCLE WITH LOWER HALF BLACK
pub const CIRCLE_WITH_LOWER_HALF_BLACK: &str = "◒";

/// U+25D3: CIRCLE WITH UPPER HALF BLACK
pub const CIRCLE_WITH_UPPER_HALF_BLACK: &str = "◓";

/// U+25D4: CIRCLE WITH UPPER RIGHT QUADRANT BLACK
pub const CIRCLE_WITH_UPPER_RIGHT_QUADRANT_BLACK: &str = "◔";

/// U+25D5: CIRCLE WITH ALL BUT UPPER LEFT QUADRANT BLACK
pub const CIRCLE_WITH_ALL_BUT_UPPER_LEFT_QUADRANT_BLACK: &str = "◕";

/// U+25D6: LEFT HALF BLACK CIRCLE
pub const LEFT_HALF_BLACK_CIRCLE: &str = "◖";

/// U+25D7: RIGHT HALF BLACK CIRCLE
pub const RIGHT_HALF_BLACK_CIRCLE: &str = "◗";

/// U+25D8: INVERSE BULLET
pub const INVERSE_BULLET: &str = "◘";

/// U+25D9: INVERSE WHITE CIRCLE
pub const INVERSE_WHITE_CIRCLE: &str = "◙";

/// U+25DA: UPPER HALF INVERSE WHITE CIRCLE
pub const UPPER_HALF_INVERSE_WHITE_CIRCLE: &str = "◚";

/// U+25DB: LOWER HALF INVERSE WHITE CIRCLE
pub const LOWER_HALF_INVERSE_WHITE_CIRCLE: &str = "◛";

/// U+25DC: UPPER LEFT QUADRANT CIRCULAR ARC
pub const UPPER_LEFT_QUADRANT_CIRCULAR_ARC: &str = "◜";

/// U+25DD: UPPER RIGHT QUADRANT CIRCULAR ARC
pub const UPPER_RIGHT_QUADRANT_CIRCULAR_ARC: &str = "◝";

/// U+25DE: LOWER RIGHT QUADRANT CIRCULAR ARC
pub const LOWER_RIGHT_QUADRANT_CIRCULAR_ARC: &str = "◞";

/// U+25DF: LOWER LEFT QUADRANT CIRCULAR ARC
pub const LOWER_LEFT_QUADRANT_CIRCULAR_ARC: &str = "◟";

/// U+25E0: UPPER HALF CIRCLE
pub const UPPER_HALF_CIRCLE: &str = "◠";

/// U+25E1: LOWER HALF CIRCLE
pub const LOWER_HALF_CIRCLE: &str = "◡";

/// U+25E2: BLACK LOWER RIGHT TRIANGLE
pub const BLACK_LOWER_RIGHT_TRIANGLE: &str = "◢";

/// U+25E3: BLACK LOWER LEFT TRIANGLE
pub const BLACK_LOWER_LEFT_TRIANGLE: &str = "◣";

/// U+25E4: BLACK UPPER LEFT TRIANGLE
pub const BLACK_UPPER_LEFT_TRIANGLE: &str = "◤";

/// U+25E5: BLACK UPPER RIGHT TRIANGLE
pub const BLACK_UPPER_RIGHT_TRIANGLE: &str = "◥";

/// U+25E6: WHITE BULLET
pub const WHITE_BULLET: &str = "◦";

/// U+25E7: SQUARE WITH LEFT HALF BLACK
pub const SQUARE_WITH_LEFT_HALF_BLACK: &str = "◧";

/// U+25E8: SQUARE WITH RIGHT HALF BLACK
pub const SQUARE_WITH_RIGHT_HALF_BLACK: &str = "◨";

/// U+25E9: SQUARE WITH UPPER LEFT DIAGONAL HALF BLACK
pub const SQUARE_WITH_UPPER_LEFT_DIAGONAL_HALF_BLACK: &str = "◩";

/// U+25EA: SQUARE WITH LOWER RIGHT DIAGONAL HALF BLACK
pub const SQUARE_WITH_LOWER_RIGHT_DIAGONAL_HALF_BLACK: &str = "◪";

/// U+25EB: WHITE SQUARE WITH VERTICAL BISECTING LINE
pub const WHITE_SQUARE_WITH_VERTICAL_BISECTING_LINE: &str = "◫";

/// U+25EC: WHITE UP-POINTING TRIANGLE WITH DOT
pub const WHITE_UP_POINTING_TRIANGLE_WITH_DOT: &str = "◬";

/// U+25ED: UP-POINTING TRIANGLE WITH LEFT HALF BLACK
pub const UP_POINTING_TRIANGLE_WITH_LEFT_HALF_BLACK: &str = "◭";

/// U+25EE: UP-POINTING TRIANGLE WITH RIGHT HALF BLACK
pub const UP_POINTING_TRIANGLE_WITH_RIGHT_HALF_BLACK: &str = "◮";

/// U+25EF: LARGE CIRCLE
pub const LARGE_CIRCLE: &str = "◯";

/// U+25F0: WHITE SQUARE WITH UPPER LEFT QUADRANT
pub const WHITE_SQUARE_WITH_UPPER_LEFT_QUADRANT: &str = "◰";

/// U+25F1: WHITE SQUARE WITH LOWER LEFT QUADRANT
pub const WHITE_SQUARE_WITH_LOWER_LEFT_QUADRANT: &str = "◱";

/// U+25F2: WHITE SQUARE WITH LOWER RIGHT QUADRANT
pub const WHITE_SQUARE_WITH_LOWER_RIGHT_QUADRANT: &str = "◲";

/// U+25F3: WHITE SQUARE WITH UPPER RIGHT QUADRANT
pub const WHITE_SQUARE_WITH_UPPER_RIGHT_QUADRANT: &str = "◳";

/// U+25F4: WHITE CIRCLE WITH UPPER LEFT QUADRANT
pub const WHITE_CIRCLE_WITH_UPPER_LEFT_QUADRANT: &str = "◴";

/// U+25F5: WHITE CIRCLE WITH LOWER LEFT QUADRANT
pub const WHITE_CIRCLE_WITH_LOWER_LEFT_QUADRANT: &str = "◵";

/// U+25F6: WHITE CIRCLE WITH LOWER RIGHT QUADRANT
pub const WHITE_CIRCLE_WITH_LOWER_RIGHT_QUADRANT: &str = "◶";

/// U+25F7: WHITE CIRCLE WITH UPPER RIGHT QUADRANT
pub const WHITE_CIRCLE_WITH_UPPER_RIGHT_QUADRANT: &str = "◷";

/// U+25F8: UPPER LEFT TRIANGLE
pub const UPPER_LEFT_TRIANGLE: &str = "◸";

/// U+25F9: UPPER RIGHT TRIANGLE
pub const UPPER_RIGHT_TRIANGLE: &str = "◹";

/// U+25FA: LOWER LEFT TRIANGLE
pub const LOWER_LEFT_TRIANGLE: &str = "◺";

/// U+25FB: WHITE MEDIUM SQUARE
pub const WHITE_MEDIUM_SQUARE: &str = "◻";

/// U+25FC: BLACK MEDIUM SQUARE
pub const BLACK_MEDIUM_SQUARE: &str = "◼";

/// U+25FD: WHITE MEDIUM SMALL SQUARE
pub const WHITE_MEDIUM_SMALL_SQUARE: &str = "◽";

/// U+25FE: BLACK MEDIUM SMALL SQUARE
pub const BLACK_MEDIUM_SMALL_SQUARE: &str = "◾";

/// U+25FF: LOWER RIGHT TRIANGLE
pub const LOWER_RIGHT_TRIANGLE: &str = "◿";

// Supplemental Arrows-A

/// U+27F0: UPWARDS QUADRUPLE ARROW
pub const UPWARDS_QUADRUPLE_ARROW: &str = "⟰";

/// U+27F1: DOWNWARDS QUADRUPLE ARROW
pub const DOWNWARDS_QUADRUPLE_ARROW: &str = "⟱";

/// U+27F2: ANTICLOCKWISE GAPPED CIRCLE ARROW
pub const ANTICLOCKWISE_GAPPED_CIRCLE_ARROW: &str = "⟲";

/// U+27F3: CLOCKWISE GAPPED CIRCLE ARROW
pub const CLOCKWISE_GAPPED_CIRCLE_ARROW: &str = "⟳";

/// U+27F4: RIGHT ARROW WITH CIRCLED PLUS
pub const RIGHT_ARROW_WITH_CIRCLED_PLUS: &str = "⟴";

/// U+27F5: LONG LEFTWARDS ARROW
pub const LONG_LEFTWARDS_ARROW: &str = "⟵";

/// U+27F6: LONG RIGHTWARDS ARROW
pub const LONG_RIGHTWARDS_ARROW: &str = "⟶";

/// U+27F7: LONG LEFT RIGHT ARROW
pub const LONG_LEFT_RIGHT_ARROW: &str = "⟷";

/// U+27F8: LONG LEFTWARDS DOUBLE ARROW
pub const LONG_LEFTWARDS_DOUBLE_ARROW: &str = "⟸";

/// U+27F9: LONG RIGHTWARDS DOUBLE ARROW
pub const LONG_RIGHTWARDS_DOUBLE_ARROW: &str = "⟹";

/// U+27FA: LONG LEFT RIGHT DOUBLE ARROW
pub const LONG_LEFT_RIGHT_DOUBLE_ARROW: &str = "⟺";

/// U+27FB: LONG LEFTWARDS ARROW FROM BAR
pub const LONG_LEFTWARDS_ARROW_FROM_BAR: &str = "⟻";

/// U+27FC: LONG RIGHTWARDS ARROW FROM BAR
pub const LONG_RIGHTWARDS_ARROW_FROM_BAR: &str = "⟼";

/// U+27FD: LONG LEFTWARDS DOUBLE ARROW FROM BAR
pub const LONG_LEFTWARDS_DOUBLE_ARROW_FROM_BAR: &str = "⟽";

/// U+27FE: LONG RIGHTWARDS DOUBLE ARROW FROM BAR
pub const LONG_RIGHTWARDS_DOUBLE_ARROW_FROM_BAR: &str = "⟾";

/// U+27FF: LONG RIGHTWARDS SQUIGGLE ARROW
pub const LONG_RIGHTWARDS_SQUIGGLE_ARROW: &str = "⟿";

/// Legacy computing

/// U+1FB00: BLOCK SEXTANT-1
pub const BLOCK_SEXTANT_1: &str = "🬀";

/// U+1FB01: BLOCK SEXTANT-2
pub const BLOCK_SEXTANT_2: &str = "🬁";

/// U+1FB02: BLOCK SEXTANT-12
pub const BLOCK_SEXTANT_12: &str = "🬂";

/// U+1FB03: BLOCK SEXTANT-3
pub const BLOCK_SEXTANT_3: &str = "🬃";

/// U+1FB04: BLOCK SEXTANT-13
pub const BLOCK_SEXTANT_13: &str = "🬄";

/// U+1FB05: BLOCK SEXTANT-23
pub const BLOCK_SEXTANT_23: &str = "🬅";

/// U+1FB06: BLOCK SEXTANT-123
pub const BLOCK_SEXTANT_123: &str = "🬆";

/// U+1FB07: BLOCK SEXTANT-4
pub const BLOCK_SEXTANT_4: &str = "🬇";

/// U+1FB08: BLOCK SEXTANT-14
pub const BLOCK_SEXTANT_14: &str = "🬈";

/// U+1FB09: BLOCK SEXTANT-24
pub const BLOCK_SEXTANT_24: &str = "🬉";

/// U+1FB0A: BLOCK SEXTANT-124
pub const BLOCK_SEXTANT_124: &str = "🬊";

/// U+1FB0B: BLOCK SEXTANT-34
pub const BLOCK_SEXTANT_34: &str = "🬋";

/// U+1FB0C: BLOCK SEXTANT-134
pub const BLOCK_SEXTANT_134: &str = "🬌";

/// U+1FB0D: BLOCK SEXTANT-234
pub const BLOCK_SEXTANT_234: &str = "🬍";

/// U+1FB0E: BLOCK SEXTANT-1234
pub const BLOCK_SEXTANT_1234: &str = "🬎";

/// U+1FB0F: BLOCK SEXTANT-5
pub const BLOCK_SEXTANT_5: &str = "🬏";

/// U+1FB10: BLOCK SEXTANT-15
pub const BLOCK_SEXTANT_15: &str = "🬐";

/// U+1FB11: BLOCK SEXTANT-25
pub const BLOCK_SEXTANT_25: &str = "🬑";

/// U+1FB12: BLOCK SEXTANT-125
pub const BLOCK_SEXTANT_125: &str = "🬒";

/// U+1FB13: BLOCK SEXTANT-35
pub const BLOCK_SEXTANT_35: &str = "🬓";

/// U+1FB14: BLOCK SEXTANT-235
pub const BLOCK_SEXTANT_235: &str = "🬔";

/// U+1FB15: BLOCK SEXTANT-1235
pub const BLOCK_SEXTANT_1235: &str = "🬕";

/// U+1FB16: BLOCK SEXTANT-45
pub const BLOCK_SEXTANT_45: &str = "🬖";

/// U+1FB17: BLOCK SEXTANT-145
pub const BLOCK_SEXTANT_145: &str = "🬗";

/// U+1FB18: BLOCK SEXTANT-245
pub const BLOCK_SEXTANT_245: &str = "🬘";

/// U+1FB19: BLOCK SEXTANT-1245
pub const BLOCK_SEXTANT_1245: &str = "🬙";

/// U+1FB1A: BLOCK SEXTANT-345
pub const BLOCK_SEXTANT_345: &str = "🬚";

/// U+1FB1B: BLOCK SEXTANT-1345
pub const BLOCK_SEXTANT_1345: &str = "🬛";

/// U+1FB1C: BLOCK SEXTANT-2345
pub const BLOCK_SEXTANT_2345: &str = "🬜";

/// U+1FB1D: BLOCK SEXTANT-12345
pub const BLOCK_SEXTANT_12345: &str = "🬝";

/// U+1FB1E: BLOCK SEXTANT-6
pub const BLOCK_SEXTANT_6: &str = "🬞";

/// U+1FB1F: BLOCK SEXTANT-16
pub const BLOCK_SEXTANT_16: &str = "🬟";

/// U+1FB20: BLOCK SEXTANT-26
pub const BLOCK_SEXTANT_26: &str = "🬠";

/// U+1FB21: BLOCK SEXTANT-126
pub const BLOCK_SEXTANT_126: &str = "🬡";

/// U+1FB22: BLOCK SEXTANT-36
pub const BLOCK_SEXTANT_36: &str = "🬢";

/// U+1FB23: BLOCK SEXTANT-136
pub const BLOCK_SEXTANT_136: &str = "🬣";

/// U+1FB24: BLOCK SEXTANT-236
pub const BLOCK_SEXTANT_236: &str = "🬤";

/// U+1FB25: BLOCK SEXTANT-1236
pub const BLOCK_SEXTANT_1236: &str = "🬥";

/// U+1FB26: BLOCK SEXTANT-46
pub const BLOCK_SEXTANT_46: &str = "🬦";

/// U+1FB27: BLOCK SEXTANT-146
pub const BLOCK_SEXTANT_146: &str = "🬧";

/// U+1FB28: BLOCK SEXTANT-1246
pub const BLOCK_SEXTANT_1246: &str = "🬨";

/// U+1FB29: BLOCK SEXTANT-346
pub const BLOCK_SEXTANT_346: &str = "🬩";

/// U+1FB2A: BLOCK SEXTANT-1346
pub const BLOCK_SEXTANT_1346: &str = "🬪";

/// U+1FB2B: BLOCK SEXTANT-2346
pub const BLOCK_SEXTANT_2346: &str = "🬫";

/// U+1FB2C: BLOCK SEXTANT-12346
pub const BLOCK_SEXTANT_12346: &str = "🬬";

/// U+1FB2D: BLOCK SEXTANT-56
pub const BLOCK_SEXTANT_56: &str = "🬭";

/// U+1FB2E: BLOCK SEXTANT-156
pub const BLOCK_SEXTANT_156: &str = "🬮";

/// U+1FB2F: BLOCK SEXTANT-256
pub const BLOCK_SEXTANT_256: &str = "🬯";

/// U+1FB30: BLOCK SEXTANT-1256
pub const BLOCK_SEXTANT_1256: &str = "🬰";

/// U+1FB31: BLOCK SEXTANT-356
pub const BLOCK_SEXTANT_356: &str = "🬱";

/// U+1FB32: BLOCK SEXTANT-1356
pub const BLOCK_SEXTANT_1356: &str = "🬲";

/// U+1FB33: BLOCK SEXTANT-2356
pub const BLOCK_SEXTANT_2356: &str = "🬳";

/// U+1FB34: BLOCK SEXTANT-12356
pub const BLOCK_SEXTANT_12356: &str = "🬴";

/// U+1FB35: BLOCK SEXTANT-456
pub const BLOCK_SEXTANT_456: &str = "🬵";

/// U+1FB36: BLOCK SEXTANT-1456
pub const BLOCK_SEXTANT_1456: &str = "🬶";

/// U+1FB37: BLOCK SEXTANT-2456
pub const BLOCK_SEXTANT_2456: &str = "🬷";

/// U+1FB38: BLOCK SEXTANT-12456
pub const BLOCK_SEXTANT_12456: &str = "🬸";

/// U+1FB39: BLOCK SEXTANT-3456
pub const BLOCK_SEXTANT_3456: &str = "🬹";

/// U+1FB3A: BLOCK SEXTANT-13456
pub const BLOCK_SEXTANT_13456: &str = "🬺";

/// U+1FB3B: BLOCK SEXTANT-23456
pub const BLOCK_SEXTANT_23456: &str = "🬻";

/// U+1FB3C: LOWER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER CENTRE
pub const LOWER_LEFT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🬼";

/// U+1FB3D: LOWER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_LOWER_RIGHT: &str = "🬽";

/// U+1FB3E: LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER CENTRE
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🬾";

/// U+1FB3F: LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_LOWER_RIGHT: &str = "🬿";

/// U+1FB40: LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO LOWER CENTRE
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_LEFT_TO_LOWER_CENTRE: &str = "🭀";

/// U+1FB41: LOWER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER CENTRE
pub const LOWER_RIGHT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_UPPER_CENTRE: &str = "🭁";

/// U+1FB42: LOWER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_UPPER_RIGHT: &str = "🭂";

/// U+1FB43: LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER CENTRE
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_UPPER_CENTRE: &str = "🭃";

/// U+1FB44: LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_UPPER_RIGHT: &str = "🭄";

/// U+1FB45: LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO UPPER CENTRE
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_LEFT_TO_UPPER_CENTRE: &str = "🭅";

/// U+1FB46: LOWER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER MIDDLE RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_UPPER_MIDDLE_RIGHT: &str = "🭆";

/// U+1FB47: LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO LOWER MIDDLE RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_CENTRE_TO_LOWER_MIDDLE_RIGHT: &str = "🭇";

/// U+1FB48: LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO LOWER MIDDLE RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_LEFT_TO_LOWER_MIDDLE_RIGHT: &str = "🭈";

/// U+1FB49: LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO UPPER MIDDLE RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_CENTRE_TO_UPPER_MIDDLE_RIGHT: &str = "🭉";

/// U+1FB4A: LOWER RIGHT BLOCK DIAGONAL LOWER LEFT TO UPPER MIDDLE RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_LEFT_TO_UPPER_MIDDLE_RIGHT: &str = "🭊";

/// U+1FB4B: LOWER RIGHT BLOCK DIAGONAL LOWER CENTRE TO UPPER RIGHT
pub const LOWER_RIGHT_BLOCK_DIAGONAL_LOWER_CENTRE_TO_UPPER_RIGHT: &str = "🭋";

/// U+1FB4C: LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO UPPER MIDDLE RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_CENTRE_TO_UPPER_MIDDLE_RIGHT: &str = "🭌";

/// U+1FB4D: LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO UPPER MIDDLE RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_LEFT_TO_UPPER_MIDDLE_RIGHT: &str = "🭍";

/// U+1FB4E: LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO LOWER MIDDLE RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_CENTRE_TO_LOWER_MIDDLE_RIGHT: &str = "🭎";

/// U+1FB4F: LOWER LEFT BLOCK DIAGONAL UPPER LEFT TO LOWER MIDDLE RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_LEFT_TO_LOWER_MIDDLE_RIGHT: &str = "🭏";

/// U+1FB50: LOWER LEFT BLOCK DIAGONAL UPPER CENTRE TO LOWER RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_CENTRE_TO_LOWER_RIGHT: &str = "🭐";

/// U+1FB51: LOWER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER MIDDLE RIGHT
pub const LOWER_LEFT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_LOWER_MIDDLE_RIGHT: &str = "🭑";

/// U+1FB52: UPPER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER CENTRE
pub const UPPER_RIGHT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🭒";

/// U+1FB53: UPPER RIGHT BLOCK DIAGONAL LOWER MIDDLE LEFT TO LOWER RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_LOWER_RIGHT: &str = "🭓";

/// U+1FB54: UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER CENTRE
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🭔";

/// U+1FB55: UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_LOWER_RIGHT: &str = "🭕";

/// U+1FB56: UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO LOWER CENTRE
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_LEFT_TO_LOWER_CENTRE: &str = "🭖";

/// U+1FB57: UPPER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER CENTRE
pub const UPPER_LEFT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_UPPER_CENTRE: &str = "🭗";

/// U+1FB58: UPPER LEFT BLOCK DIAGONAL UPPER MIDDLE LEFT TO UPPER RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_UPPER_RIGHT: &str = "🭘";

/// U+1FB59: UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER CENTRE
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_UPPER_CENTRE: &str = "🭙";

/// U+1FB5A: UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_UPPER_RIGHT: &str = "🭚";

/// U+1FB5B: UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO UPPER CENTRE
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_LEFT_TO_UPPER_CENTRE: &str = "🭛";

/// U+1FB5C: UPPER LEFT BLOCK DIAGONAL LOWER MIDDLE LEFT TO UPPER MIDDLE RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_MIDDLE_LEFT_TO_UPPER_MIDDLE_RIGHT: &str = "🭜";

/// U+1FB5D: UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO LOWER MIDDLE RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_CENTRE_TO_LOWER_MIDDLE_RIGHT: &str = "🭝";

/// U+1FB5E: UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO LOWER MIDDLE RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_LEFT_TO_LOWER_MIDDLE_RIGHT: &str = "🭞";

/// U+1FB5F: UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO UPPER MIDDLE RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_CENTRE_TO_UPPER_MIDDLE_RIGHT: &str = "🭟";

/// U+1FB60: UPPER LEFT BLOCK DIAGONAL LOWER LEFT TO UPPER MIDDLE RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_LEFT_TO_UPPER_MIDDLE_RIGHT: &str = "🭠";

/// U+1FB61: UPPER LEFT BLOCK DIAGONAL LOWER CENTRE TO UPPER RIGHT
pub const UPPER_LEFT_BLOCK_DIAGONAL_LOWER_CENTRE_TO_UPPER_RIGHT: &str = "🭡";

/// U+1FB62: UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO UPPER MIDDLE RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_CENTRE_TO_UPPER_MIDDLE_RIGHT: &str = "🭢";

/// U+1FB63: UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO UPPER MIDDLE RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_LEFT_TO_UPPER_MIDDLE_RIGHT: &str = "🭣";

/// U+1FB64: UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO LOWER MIDDLE RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_CENTRE_TO_LOWER_MIDDLE_RIGHT: &str = "🭤";

/// U+1FB65: UPPER RIGHT BLOCK DIAGONAL UPPER LEFT TO LOWER MIDDLE RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_LEFT_TO_LOWER_MIDDLE_RIGHT: &str = "🭥";

/// U+1FB66: UPPER RIGHT BLOCK DIAGONAL UPPER CENTRE TO LOWER RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_CENTRE_TO_LOWER_RIGHT: &str = "🭦";

/// U+1FB67: UPPER RIGHT BLOCK DIAGONAL UPPER MIDDLE LEFT TO LOWER MIDDLE RIGHT
pub const UPPER_RIGHT_BLOCK_DIAGONAL_UPPER_MIDDLE_LEFT_TO_LOWER_MIDDLE_RIGHT: &str = "🭧";

/// U+1FB68: UPPER AND RIGHT AND LOWER TRIANGULAR THREE QUARTERS BLOCK
pub const UPPER_AND_RIGHT_AND_LOWER_TRIANGULAR_THREE_QUARTERS_BLOCK: &str = "🭨";

/// U+1FB69: LEFT AND LOWER AND RIGHT TRIANGULAR THREE QUARTERS BLOCK
pub const LEFT_AND_LOWER_AND_RIGHT_TRIANGULAR_THREE_QUARTERS_BLOCK: &str = "🭩";

/// U+1FB6A: UPPER AND LEFT AND LOWER TRIANGULAR THREE QUARTERS BLOCK
pub const UPPER_AND_LEFT_AND_LOWER_TRIANGULAR_THREE_QUARTERS_BLOCK: &str = "🭪";

/// U+1FB6B: LEFT AND UPPER AND RIGHT TRIANGULAR THREE QUARTERS BLOCK
pub const LEFT_AND_UPPER_AND_RIGHT_TRIANGULAR_THREE_QUARTERS_BLOCK: &str = "🭫";

/// U+1FB6C: LEFT TRIANGULAR ONE QUARTER BLOCK
pub const LEFT_TRIANGULAR_ONE_QUARTER_BLOCK: &str = "🭬";

/// U+1FB6D: UPPER TRIANGULAR ONE QUARTER BLOCK
pub const UPPER_TRIANGULAR_ONE_QUARTER_BLOCK: &str = "🭭";

/// U+1FB6E: RIGHT TRIANGULAR ONE QUARTER BLOCK
pub const RIGHT_TRIANGULAR_ONE_QUARTER_BLOCK: &str = "🭮";

/// U+1FB6F: LOWER TRIANGULAR ONE QUARTER BLOCK
pub const LOWER_TRIANGULAR_ONE_QUARTER_BLOCK: &str = "🭯";

/// U+1FB70: VERTICAL ONE EIGHTH BLOCK-2
pub const VERTICAL_ONE_EIGHTH_BLOCK_2: &str = "🭰";

/// U+1FB71: VERTICAL ONE EIGHTH BLOCK-3
pub const VERTICAL_ONE_EIGHTH_BLOCK_3: &str = "🭱";

/// U+1FB72: VERTICAL ONE EIGHTH BLOCK-4
pub const VERTICAL_ONE_EIGHTH_BLOCK_4: &str = "🭲";

/// U+1FB73: VERTICAL ONE EIGHTH BLOCK-5
pub const VERTICAL_ONE_EIGHTH_BLOCK_5: &str = "🭳";

/// U+1FB74: VERTICAL ONE EIGHTH BLOCK-6
pub const VERTICAL_ONE_EIGHTH_BLOCK_6: &str = "🭴";

/// U+1FB75: VERTICAL ONE EIGHTH BLOCK-7
pub const VERTICAL_ONE_EIGHTH_BLOCK_7: &str = "🭵";

/// U+1FB76: HORIZONTAL ONE EIGHTH BLOCK-2
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_2: &str = "🭶";

/// U+1FB77: HORIZONTAL ONE EIGHTH BLOCK-3
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_3: &str = "🭷";

/// U+1FB78: HORIZONTAL ONE EIGHTH BLOCK-4
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_4: &str = "🭸";

/// U+1FB79: HORIZONTAL ONE EIGHTH BLOCK-5
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_5: &str = "🭹";

/// U+1FB7A: HORIZONTAL ONE EIGHTH BLOCK-6
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_6: &str = "🭺";

/// U+1FB7B: HORIZONTAL ONE EIGHTH BLOCK-7
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_7: &str = "🭻";

/// U+1FB7C: LEFT AND LOWER ONE EIGHTH BLOCK
pub const LEFT_AND_LOWER_ONE_EIGHTH_BLOCK: &str = "🭼";

/// U+1FB7D: LEFT AND UPPER ONE EIGHTH BLOCK
pub const LEFT_AND_UPPER_ONE_EIGHTH_BLOCK: &str = "🭽";

/// U+1FB7E: RIGHT AND UPPER ONE EIGHTH BLOCK
pub const RIGHT_AND_UPPER_ONE_EIGHTH_BLOCK: &str = "🭾";

/// U+1FB7F: RIGHT AND LOWER ONE EIGHTH BLOCK
pub const RIGHT_AND_LOWER_ONE_EIGHTH_BLOCK: &str = "🭿";

/// U+1FB80: UPPER AND LOWER ONE EIGHTH BLOCK
pub const UPPER_AND_LOWER_ONE_EIGHTH_BLOCK: &str = "🮀";

/// U+1FB81: HORIZONTAL ONE EIGHTH BLOCK-1358
pub const HORIZONTAL_ONE_EIGHTH_BLOCK_1358: &str = "🮁";

/// U+1FB82: UPPER ONE QUARTER BLOCK
pub const UPPER_ONE_QUARTER_BLOCK: &str = "🮂";

/// U+1FB83: UPPER THREE EIGHTHS BLOCK
pub const UPPER_THREE_EIGHTHS_BLOCK: &str = "🮃";

/// U+1FB84: UPPER FIVE EIGHTHS BLOCK
pub const UPPER_FIVE_EIGHTHS_BLOCK: &str = "🮄";

/// U+1FB85: UPPER THREE QUARTERS BLOCK
pub const UPPER_THREE_QUARTERS_BLOCK: &str = "🮅";

/// U+1FB86: UPPER SEVEN EIGHTHS BLOCK
pub const UPPER_SEVEN_EIGHTHS_BLOCK: &str = "🮆";

/// U+1FB87: RIGHT ONE QUARTER BLOCK
pub const RIGHT_ONE_QUARTER_BLOCK: &str = "🮇";

/// U+1FB88: RIGHT THREE EIGHTHS BLOCK
pub const RIGHT_THREE_EIGHTHS_BLOCK: &str = "🮈";

/// U+1FB89: RIGHT FIVE EIGHTHS BLOCK
pub const RIGHT_FIVE_EIGHTHS_BLOCK: &str = "🮉";

/// U+1FB8A: RIGHT THREE QUARTERS BLOCK
pub const RIGHT_THREE_QUARTERS_BLOCK: &str = "🮊";

/// U+1FB8B: RIGHT SEVEN EIGHTHS BLOCK
pub const RIGHT_SEVEN_EIGHTHS_BLOCK: &str = "🮋";

/// U+1FB8C: LEFT HALF MEDIUM SHADE
pub const LEFT_HALF_MEDIUM_SHADE: &str = "🮌";

/// U+1FB8D: RIGHT HALF MEDIUM SHADE
pub const RIGHT_HALF_MEDIUM_SHADE: &str = "🮍";

/// U+1FB8E: UPPER HALF MEDIUM SHADE
pub const UPPER_HALF_MEDIUM_SHADE: &str = "🮎";

/// U+1FB8F: LOWER HALF MEDIUM SHADE
pub const LOWER_HALF_MEDIUM_SHADE: &str = "🮏";

/// U+1FB90: INVERSE MEDIUM SHADE
pub const INVERSE_MEDIUM_SHADE: &str = "🮐";

/// U+1FB91: UPPER HALF BLOCK AND LOWER HALF INVERSE MEDIUM SHADE
pub const UPPER_HALF_BLOCK_AND_LOWER_HALF_INVERSE_MEDIUM_SHADE: &str = "🮑";

/// U+1FB92: UPPER HALF INVERSE MEDIUM SHADE AND LOWER HALF BLOCK
pub const UPPER_HALF_INVERSE_MEDIUM_SHADE_AND_LOWER_HALF_BLOCK: &str = "🮒";

/// U+1FB94: LEFT HALF INVERSE MEDIUM SHADE AND RIGHT HALF BLOCK
pub const LEFT_HALF_INVERSE_MEDIUM_SHADE_AND_RIGHT_HALF_BLOCK: &str = "🮔";

/// U+1FB95: CHECKER BOARD FILL
pub const CHECKER_BOARD_FILL: &str = "🮕";

/// U+1FB96: INVERSE CHECKER BOARD FILL
pub const INVERSE_CHECKER_BOARD_FILL: &str = "🮖";

/// U+1FB97: HEAVY HORIZONTAL FILL
pub const HEAVY_HORIZONTAL_FILL: &str = "🮗";

/// U+1FB98: UPPER LEFT TO LOWER RIGHT FILL
pub const UPPER_LEFT_TO_LOWER_RIGHT_FILL: &str = "🮘";

/// U+1FB99: UPPER RIGHT TO LOWER LEFT FILL
pub const UPPER_RIGHT_TO_LOWER_LEFT_FILL: &str = "🮙";

/// U+1FB9A: UPPER AND LOWER TRIANGULAR HALF BLOCK
pub const UPPER_AND_LOWER_TRIANGULAR_HALF_BLOCK: &str = "🮚";

/// U+1FB9B: LEFT AND RIGHT TRIANGULAR HALF BLOCK
pub const LEFT_AND_RIGHT_TRIANGULAR_HALF_BLOCK: &str = "🮛";

/// U+1FB9C: UPPER LEFT TRIANGULAR MEDIUM SHADE
pub const UPPER_LEFT_TRIANGULAR_MEDIUM_SHADE: &str = "🮜";

/// U+1FB9D: UPPER RIGHT TRIANGULAR MEDIUM SHADE
pub const UPPER_RIGHT_TRIANGULAR_MEDIUM_SHADE: &str = "🮝";

/// U+1FB9E: LOWER RIGHT TRIANGULAR MEDIUM SHADE
pub const LOWER_RIGHT_TRIANGULAR_MEDIUM_SHADE: &str = "🮞";

/// U+1FB9F: LOWER LEFT TRIANGULAR MEDIUM SHADE
pub const LOWER_LEFT_TRIANGULAR_MEDIUM_SHADE: &str = "🮟";

/// U+1FBA0: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_LEFT: &str = "🮠";

/// U+1FBA1: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_RIGHT: &str = "🮡";

/// U+1FBA2: BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🮢";

/// U+1FBA3: BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_RIGHT_TO_LOWER_CENTRE: &str = "🮣";

/// U+1FBA4: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🮤";

/// U+1FBA5: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_RIGHT_TO_LOWER_CENTRE: &str = "🮥";

/// U+1FBA6: BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER CENTRE TO MIDDLE RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_LEFT_TO_LOWER_CENTRE_TO_MIDDLE_RIGHT: &str = "🮦";

/// U+1FBA7: BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO UPPER CENTRE TO MIDDLE RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_LEFT_TO_UPPER_CENTRE_TO_MIDDLE_RIGHT: &str = "🮧";

/// U+1FBA8: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT AND MIDDLE RIGHT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_LEFT_AND_MIDDLE_RIGHT_TO_LOWER_CENTRE: &str = "🮨";

/// U+1FBA9: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT AND MIDDLE LEFT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_RIGHT_AND_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🮩";

/// U+1FBAA: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE TO MIDDLE LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_RIGHT_TO_LOWER_CENTRE_TO_MIDDLE_LEFT: &str = "🮪";

/// U+1FBAB: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE TO MIDDLE RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_MIDDLE_LEFT_TO_LOWER_CENTRE_TO_MIDDLE_RIGHT: &str = "🮫";

/// U+1FBAC: BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO UPPER CENTRE TO MIDDLE RIGHT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_LEFT_TO_UPPER_CENTRE_TO_MIDDLE_RIGHT_TO_LOWER_CENTRE: &str = "🮬";

/// U+1FBAD: BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO UPPER CENTRE TO MIDDLE LEFT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_RIGHT_TO_UPPER_CENTRE_TO_MIDDLE_LEFT_TO_LOWER_CENTRE: &str = "🮭";

/// U+1FBAE: BOX DRAWINGS LIGHT DIAGONAL DIAMOND
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_DIAMOND: &str = "🮮";

/// U+1FBAF: BOX DRAWINGS LIGHT HORIZONTAL WITH VERTICAL STROKE
pub const BOX_DRAWINGS_LIGHT_HORIZONTAL_WITH_VERTICAL_STROKE: &str = "🮯";

/// U+1FBB0: ARROWHEAD-SHAPED POINTER
pub const ARROWHEAD_SHAPED_POINTER: &str = "🮰";

/// U+1FBB1: INVERSE CHECK MARK
pub const INVERSE_CHECK_MARK: &str = "🮱";

/// U+1FBB2: LEFT HALF RUNNING MAN
pub const LEFT_HALF_RUNNING_MAN: &str = "🮲";

/// U+1FBB3: RIGHT HALF RUNNING MAN
pub const RIGHT_HALF_RUNNING_MAN: &str = "🮳";

/// U+1FBB4: INVERSE DOWNWARDS ARROW WITH TIP LEFTWARDS
pub const INVERSE_DOWNWARDS_ARROW_WITH_TIP_LEFTWARDS: &str = "🮴";

/// U+1FBB5: LEFTWARDS ARROW AND UPPER AND LOWER ONE EIGHTH BLOCK
pub const LEFTWARDS_ARROW_AND_UPPER_AND_LOWER_ONE_EIGHTH_BLOCK: &str = "🮵";

/// U+1FBB6: RIGHTWARDS ARROW AND UPPER AND LOWER ONE EIGHTH BLOCK
pub const RIGHTWARDS_ARROW_AND_UPPER_AND_LOWER_ONE_EIGHTH_BLOCK: &str = "🮶";

/// U+1FBB7: DOWNWARDS ARROW AND RIGHT ONE EIGHTH BLOCK
pub const DOWNWARDS_ARROW_AND_RIGHT_ONE_EIGHTH_BLOCK: &str = "🮷";

/// U+1FBB8: UPWARDS ARROW AND RIGHT ONE EIGHTH BLOCK
pub const UPWARDS_ARROW_AND_RIGHT_ONE_EIGHTH_BLOCK: &str = "🮸";

/// U+1FBB9: LEFT HALF FOLDER
pub const LEFT_HALF_FOLDER: &str = "🮹";

/// U+1FBBA: RIGHT HALF FOLDER
pub const RIGHT_HALF_FOLDER: &str = "🮺";

/// U+1FBBB: VOIDED GREEK CROSS
pub const VOIDED_GREEK_CROSS: &str = "🮻";

/// U+1FBBC: RIGHT OPEN SQUARED DOT
pub const RIGHT_OPEN_SQUARED_DOT: &str = "🮼";

/// U+1FBBD: NEGATIVE DIAGONAL CROSS
pub const NEGATIVE_DIAGONAL_CROSS: &str = "🮽";

/// U+1FBBE: NEGATIVE DIAGONAL MIDDLE RIGHT TO LOWER CENTRE
pub const NEGATIVE_DIAGONAL_MIDDLE_RIGHT_TO_LOWER_CENTRE: &str = "🮾";

/// U+1FBBF: NEGATIVE DIAGONAL DIAMOND
pub const NEGATIVE_DIAGONAL_DIAMOND: &str = "🮿";

/// U+1FBC0: WHITE HEAVY SALTIRE WITH ROUNDED CORNERS
pub const WHITE_HEAVY_SALTIRE_WITH_ROUNDED_CORNERS: &str = "🯀";

/// U+1FBC1: LEFT THIRD WHITE RIGHT POINTING INDEX
pub const LEFT_THIRD_WHITE_RIGHT_POINTING_INDEX: &str = "🯁";

/// U+1FBC2: MIDDLE THIRD WHITE RIGHT POINTING INDEX
pub const MIDDLE_THIRD_WHITE_RIGHT_POINTING_INDEX: &str = "🯂";

/// U+1FBC3: RIGHT THIRD WHITE RIGHT POINTING INDEX
pub const RIGHT_THIRD_WHITE_RIGHT_POINTING_INDEX: &str = "🯃";

/// U+1FBC4: NEGATIVE SQUARED QUESTION MARK
pub const NEGATIVE_SQUARED_QUESTION_MARK: &str = "🯄";

/// U+1FBC5: STICK FIGURE
pub const STICK_FIGURE: &str = "🯅";

/// U+1FBC6: STICK FIGURE WITH ARMS RAISED
pub const STICK_FIGURE_WITH_ARMS_RAISED: &str = "🯆";

/// U+1FBC7: STICK FIGURE LEANING LEFT
pub const STICK_FIGURE_LEANING_LEFT: &str = "🯇";

/// U+1FBC8: STICK FIGURE LEANING RIGHT
pub const STICK_FIGURE_LEANING_RIGHT: &str = "🯈";

/// U+1FBC9: STICK FIGURE WITH DRESS
pub const STICK_FIGURE_WITH_DRESS: &str = "🯉";

/// U+1FBCA: WHITE UP-POINTING CHEVRON
pub const WHITE_UP_POINTING_CHEVRON: &str = "🯊";

/// U+1FBCB: WHITE CROSS MARK
pub const WHITE_CROSS_MARK: &str = "🯋";

/// U+1FBCC: RAISED SMALL LEFT SQUARE BRACKET
pub const RAISED_SMALL_LEFT_SQUARE_BRACKET: &str = "🯌";

/// U+1FBCD: BLACK SMALL UP-POINTING CHEVRON
pub const BLACK_SMALL_UP_POINTING_CHEVRON: &str = "🯍";

/// U+1FBCE: LEFT TWO THIRDS BLOCK
pub const LEFT_TWO_THIRDS_BLOCK: &str = "🯎";

/// U+1FBCF: LEFT ONE THIRD BLOCK
pub const LEFT_ONE_THIRD_BLOCK: &str = "🯏";

/// U+1FBD0: BOX DRAWINGS LIGHT DIAGONAL MIDDLE RIGHT TO LOWER LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_RIGHT_TO_LOWER_LEFT: &str = "🯐";

/// U+1FBD1: BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO MIDDLE LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_MIDDLE_LEFT: &str = "🯑";

/// U+1FBD2: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_MIDDLE_RIGHT: &str = "🯒";

/// U+1FBD3: BOX DRAWINGS LIGHT DIAGONAL MIDDLE LEFT TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_MIDDLE_LEFT_TO_LOWER_RIGHT: &str = "🯓";

/// U+1FBD4: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_CENTRE: &str = "🯔";

/// U+1FBD5: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_LOWER_RIGHT: &str = "🯕";

/// U+1FBD6: BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER CENTRE
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_CENTRE: &str = "🯖";

/// U+1FBD7: BOX DRAWINGS LIGHT DIAGONAL UPPER CENTRE TO LOWER LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_CENTRE_TO_LOWER_LEFT: &str = "🯗";

/// U+1FBD8: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE CENTRE TO UPPER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_MIDDLE_CENTRE_TO_UPPER_RIGHT: &str = "🯘";

/// U+1FBD9: BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO MIDDLE CENTRE TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_MIDDLE_CENTRE_TO_LOWER_RIGHT: &str = "🯙";

/// U+1FBDA: BOX DRAWINGS LIGHT DIAGONAL LOWER LEFT TO MIDDLE CENTRE TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_LOWER_LEFT_TO_MIDDLE_CENTRE_TO_LOWER_RIGHT: &str = "🯚";

/// U+1FBDB: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE CENTRE TO LOWER LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_MIDDLE_CENTRE_TO_LOWER_LEFT: &str = "🯛";

/// U+1FBDC: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER CENTRE TO UPPER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_CENTRE_TO_UPPER_RIGHT: &str = "🯜";

/// U+1FBDD: BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO MIDDLE LEFT TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_MIDDLE_LEFT_TO_LOWER_RIGHT: &str = "🯝";

/// U+1FBDE: BOX DRAWINGS LIGHT DIAGONAL LOWER LEFT TO UPPER CENTRE TO LOWER RIGHT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_LOWER_LEFT_TO_UPPER_CENTRE_TO_LOWER_RIGHT: &str = "🯞";

/// U+1FBDF: BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO MIDDLE RIGHT TO LOWER LEFT
pub const BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_MIDDLE_RIGHT_TO_LOWER_LEFT: &str = "🯟";

/// U+1FBE0: TOP JUSTIFIED LOWER HALF WHITE CIRCLE
pub const TOP_JUSTIFIED_LOWER_HALF_WHITE_CIRCLE: &str = "🯠";

/// U+1FBE1: RIGHT JUSTIFIED LEFT HALF WHITE CIRCLE
pub const RIGHT_JUSTIFIED_LEFT_HALF_WHITE_CIRCLE: &str = "🯡";

/// U+1FBE2: BOTTOM JUSTIFIED UPPER HALF WHITE CIRCLE
pub const BOTTOM_JUSTIFIED_UPPER_HALF_WHITE_CIRCLE: &str = "🯢";

/// U+1FBE3: LEFT JUSTIFIED RIGHT HALF WHITE CIRCLE
pub const LEFT_JUSTIFIED_RIGHT_HALF_WHITE_CIRCLE: &str = "🯣";

/// U+1FBE4: UPPER CENTRE ONE QUARTER BLOCK
pub const UPPER_CENTRE_ONE_QUARTER_BLOCK: &str = "🯤";

/// U+1FBE5: LOWER CENTRE ONE QUARTER BLOCK
pub const LOWER_CENTRE_ONE_QUARTER_BLOCK: &str = "🯥";

/// U+1FBE6: MIDDLE LEFT ONE QUARTER BLOCK
pub const MIDDLE_LEFT_ONE_QUARTER_BLOCK: &str = "🯦";

/// U+1FBE7: MIDDLE RIGHT ONE QUARTER BLOCK
pub const MIDDLE_RIGHT_ONE_QUARTER_BLOCK: &str = "🯧";

/// U+1FBE8: TOP JUSTIFIED LOWER HALF BLACK CIRCLE
pub const TOP_JUSTIFIED_LOWER_HALF_BLACK_CIRCLE: &str = "🯨";

/// U+1FBE9: RIGHT JUSTIFIED LEFT HALF BLACK CIRCLE
pub const RIGHT_JUSTIFIED_LEFT_HALF_BLACK_CIRCLE: &str = "🯩";

/// U+1FBEA: BOTTOM JUSTIFIED UPPER HALF BLACK CIRCLE
pub const BOTTOM_JUSTIFIED_UPPER_HALF_BLACK_CIRCLE: &str = "🯪";

/// U+1FBEB: LEFT JUSTIFIED RIGHT HALF BLACK CIRCLE
pub const LEFT_JUSTIFIED_RIGHT_HALF_BLACK_CIRCLE: &str = "🯫";

/// U+1FBEC: TOP RIGHT JUSTIFIED LOWER LEFT QUARTER BLACK CIRCLE
pub const TOP_RIGHT_JUSTIFIED_LOWER_LEFT_QUARTER_BLACK_CIRCLE: &str = "🯬";

/// U+1FBED: BOTTOM LEFT JUSTIFIED UPPER RIGHT QUARTER BLACK CIRCLE
pub const BOTTOM_LEFT_JUSTIFIED_UPPER_RIGHT_QUARTER_BLACK_CIRCLE: &str = "🯭";

/// U+1FBEE: BOTTOM RIGHT JUSTIFIED UPPER LEFT QUARTER BLACK CIRCLE
pub const BOTTOM_RIGHT_JUSTIFIED_UPPER_LEFT_QUARTER_BLACK_CIRCLE: &str = "🯮";

/// U+1FBEF: TOP LEFT JUSTIFIED LOWER RIGHT QUARTER BLACK CIRCLE
pub const TOP_LEFT_JUSTIFIED_LOWER_RIGHT_QUARTER_BLACK_CIRCLE: &str = "🯯";

/// U+1FBF0: SEGMENTED DIGIT ZERO
pub const SEGMENTED_DIGIT_ZERO: &str = "🯰";

/// U+1FBF1: SEGMENTED DIGIT ONE
pub const SEGMENTED_DIGIT_ONE: &str = "🯱";

/// U+1FBF2: SEGMENTED DIGIT TWO
pub const SEGMENTED_DIGIT_TWO: &str = "🯲";

/// U+1FBF3: SEGMENTED DIGIT THREE
pub const SEGMENTED_DIGIT_THREE: &str = "🯳";

/// U+1FBF4: SEGMENTED DIGIT FOUR
pub const SEGMENTED_DIGIT_FOUR: &str = "🯴";

/// U+1FBF5: SEGMENTED DIGIT FIVE
pub const SEGMENTED_DIGIT_FIVE: &str = "🯵";

/// U+1FBF6: SEGMENTED DIGIT SIX
pub const SEGMENTED_DIGIT_SIX: &str = "🯶";

/// U+1FBF7: SEGMENTED DIGIT SEVEN
pub const SEGMENTED_DIGIT_SEVEN: &str = "🯷";

/// U+1FBF8: SEGMENTED DIGIT EIGHT
pub const SEGMENTED_DIGIT_EIGHT: &str = "🯸";

/// U+1FBF9: SEGMENTED DIGIT NINE
pub const SEGMENTED_DIGIT_NINE: &str = "🯹";

/// U+1FBFA: ALARM BELL SYMBOL
pub const ALARM_BELL_SYMBOL: &str = "२";
